failed.message=Press 'space' to continue ...
failed.title=Try again
ready.title=Are you ready?
ready.press_1=Press
ready.press_2=and
placeholder.message=Press 'space' to continue ...
victory.message=Press 'space' to continue ...
victory.title=VICTORY! :)
